"use client"

import { useEffect, useRef } from "react"
import { Shield, Database, Lock, FileCheck } from "lucide-react"

const pillars = [
  {
    icon: FileCheck,
    title: "International Evidentiary Architecture",
    description:
      "The three-pillar framework — temporal lock, automated rationale, zero reconstruction — is validated against ICC arbitration standards. Records generated by Monakes are structured to meet the documentation requirements of international dispute resolution proceedings, not just internal audit.",
  },
  {
    icon: Database,
    title: "Client-Sovereign Infrastructure",
    description:
      "Monakes deploys on the client\u2019s own controlled environment. In-country Azure regions, government private cloud, on-premise — the institution determines the hosting architecture. No tender data, evaluation record, or institutional information is held in or transmitted through Monakes-operated infrastructure.",
  },
  {
    icon: Lock,
    title: "Jurisdiction-Adaptable Compliance",
    description:
      "The platform\u2019s compliance architecture is configurable to national procurement law frameworks. It is not locked to a single regulatory environment. Deployment in a new jurisdiction means configuring to that jurisdiction\u2019s standards — not rebuilding the platform.",
  },
  {
    icon: Shield,
    title: "Access Control & Data Integrity",
    description:
      "Evaluator identity, scoring actions, timestamps, and amendments are logged, attributed, and immutable. The record that existed at the moment of decision is the record that exists at the moment of challenge. Nothing in between can alter it.",
  },
]

export function ProcurementCompliance() {
  const sectionRef = useRef<HTMLElement>(null)
  const labelRef = useRef<HTMLSpanElement>(null)
  const headingRef = useRef<HTMLHeadingElement>(null)
  const subRef = useRef<HTMLParagraphElement>(null)
  const cardsRef = useRef<(HTMLDivElement | null)[]>([])

  useEffect(() => {
    let ctx: ReturnType<typeof import("gsap")["gsap"]["context"]> | undefined
    async function init() {
      const { gsap } = await import("gsap")
      const { ScrollTrigger } = await import("gsap/ScrollTrigger")
      gsap.registerPlugin(ScrollTrigger)

      ctx = gsap.context(() => {
        const tl = gsap.timeline({
          scrollTrigger: {
            trigger: sectionRef.current,
            start: "top 75%",
            toggleActions: "play none none none",
          },
        })

        tl.fromTo(
          labelRef.current,
          { opacity: 0, y: 20 },
          { opacity: 1, y: 0, duration: 0.5, ease: "power3.out" }
        )
          .fromTo(
            headingRef.current,
            { opacity: 0, y: 30 },
            { opacity: 1, y: 0, duration: 0.7, ease: "power3.out" },
            "-=0.2"
          )
          .fromTo(
            subRef.current,
            { opacity: 0, y: 20 },
            { opacity: 1, y: 0, duration: 0.5, ease: "power3.out" },
            "-=0.3"
          )

        cardsRef.current.filter(Boolean).forEach((card, i) => {
          tl.fromTo(
            card,
            { opacity: 0, y: 30, scale: 0.97 },
            {
              opacity: 1,
              y: 0,
              scale: 1,
              duration: 0.6,
              ease: "power3.out",
            },
            `-=${i === 0 ? 0.2 : 0.45}`
          )
        })
      }, sectionRef)
    }
    init()
    return () => ctx?.revert()
  }, [])

  return (
    <section
      ref={sectionRef}
      aria-label="Compliance and security"
      className="relative px-6 py-24 lg:py-32 overflow-hidden"
    >
      <div className="absolute inset-0 bg-[#F7F5F2]" />

      <div className="relative z-10 max-w-7xl mx-auto">
        <div className="max-w-2xl mb-16">
          <span
            ref={labelRef}
            className="text-xs font-semibold tracking-[0.2em] uppercase text-[#8A1538] mb-6 block opacity-0"
          >
            Compliance &amp; Security
          </span>
          <h2
            ref={headingRef}
            className="text-3xl sm:text-4xl lg:text-[2.75rem] font-bold text-[#1A1A1A] leading-tight mb-4 opacity-0"
            style={{ fontFamily: "var(--font-heading)" }}
          >
            A system that generates legal evidence is held to a legal standard.
            Ours is.
          </h2>
          <p
            ref={subRef}
            className="text-base text-[#5A5A5A] leading-relaxed opacity-0"
          >
            Monakes\u2019 output is not a report. It is an evidentiary record —
            the kind that gets submitted to arbitral tribunals, reviewed by audit
            bodies, and scrutinized in formal procurement challenges. The
            infrastructure behind it is built accordingly.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          {pillars.map((pillar, i) => {
            const Icon = pillar.icon
            return (
              <div
                key={pillar.title}
                ref={(el) => {
                  cardsRef.current[i] = el
                }}
                className="group relative p-8 lg:p-10 rounded-xl bg-white border border-[#1A1A1A]/6 hover:border-[#8A1538]/20 transition-all duration-500 opacity-0"
              >
                <div className="flex items-start gap-5">
                  <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-[#8A1538]/8 flex items-center justify-center group-hover:bg-[#8A1538]/12 transition-colors duration-300">
                    <Icon className="w-5 h-5 text-[#8A1538]" />
                  </div>
                  <div>
                    <h3
                      className="text-lg font-bold text-[#1A1A1A] mb-3"
                      style={{ fontFamily: "var(--font-heading)" }}
                    >
                      {pillar.title}
                    </h3>
                    <p className="text-sm text-[#5A5A5A] leading-relaxed">
                      {pillar.description}
                    </p>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      </div>
    </section>
  )
}
